# Generated by Django 5.0.1 on 2024-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='repeatedpayment',
            name='amount',
        ),
        migrations.AddField(
            model_name='onetimepayment',
            name='budgeted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='onetimepayment',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repeatedpayment',
            name='budgeted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repeatedpayment',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
