# Generated by Django 5.0.1 on 2024-01-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0002_remove_onetimepayment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepayment',
            name='budgeted',
        ),
        migrations.RemoveField(
            model_name='repeatedpayment',
            name='budgeted',
        ),
        migrations.AddField(
            model_name='category',
            name='budgeted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='category',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
