# Generated by Django 5.0.1 on 2024-01-18 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0004_category_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepayment',
            name='source',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='repeatedpayment',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='repeatedpayment',
            name='next_payment_date',
            field=models.DateField(default=datetime.date(2024, 1, 18)),
        ),
        migrations.AlterField(
            model_name='repeatedpayment',
            name='source',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
