# Generated by Django 5.0.1 on 2024-01-19 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0005_alter_onetimepayment_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatedpayment',
            name='next_payment_date',
            field=models.DateField(default=datetime.date(2024, 1, 19)),
        ),
    ]
